Repository nrfta/eslint-config, pull requests merged in 2023-07, with the labels that each got.

#50 added no-conosle rule
  packages/eslint-config/index.js
Labels: Type: Refactor

#51 dependencies: Upgrade all packages to latest
  .github/workflows/ci.yml
  package.json
  packages/eslint-config-ember/package.json
  packages/eslint-config-typescript/package.json
  packages/eslint-config/package.json
  yarn.lock
Labels: Type: Dependencies

#52 bug: remove usage of removed config from typescript eslint
  packages/eslint-config-typescript/index.js
Labels: Type: Bug

#53 feat: remove rules that depends on tsconfig
  packages/eslint-config-typescript/index.js
Labels: Type: Enhancement
